apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-10-31T04:00:20Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
  
---

kubectl create clusterrolebinding "kevin-cluster-admin" --clusterrole cluster-admin --user "kevin@gmail.com"

kubectl create clusterrole "impersonate-kevinlia" --verb impersonate --resource users --resource-name "kevin@gmail.com"

kubectl create clusterrolebinding "connect-agent-impersonate-kevinlia" --clusterrole "impersonate-kevinlia" --serviceaccount "gke-connect:connect-agent-sa"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters





  
