apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
   app: App1
   function: front-end
spec:
 containers:
   - name: myapp
     image: nginx
     ports:
     - containersPort: 8080
     

#kubectl get pods --selector app=App1
#kubectl get all --selector env=prod,bu=finance,tier=frontend

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: simple-webapp
 labels:
   app: App1
   function: Front-end
spec:
 replicas: 2
 selector:
   matchLabels:
     app: App1
 template:
   metadata:
     name: simple-webapp
     labels:
       app: App1
       function: Front-end
   spec:
     containers:
      - name: simple-webapp
        image: simple-webapp
        ports:
        - containersPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: App1
  ports:
  - protocol: Tcp
    port: 80
    targetPort: 9376

---
  
  
  
  
  
  
  
  
  
        
        
        
        
        
        
        
        