apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: bxlysanWw=
  DB_User: htyahNn==
  DB_Password: cGfhajnHn
  
#echo -n "mysql" | base64
#echo -n "bxlysanWw=" | base64 --decode

#kubectl get secrets
#kubectl describe secrets
#kubectl get secret app-secret -o yaml

---

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    app: simple-webapp-color
spec:
  conatiners:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
            
            
            
---

     env: 
       - name: DB_Password
         valueFrom:
           secretRef:
              name: app-secret
              key: DB_Password
           
            










