#kubectl create serviceaccount dashboard-sa
#kubectl get serviceaccount
#kubectl describe serviceaccount dashboard-sa
#kubectl describe secret dashboard-sa-token-kbbdm

apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard
spec:
  containers:
    - name: my-kubernetes-dashboard
      image: my-kubernetes-dashboard
  serviceAccountName: dashboard-sa 
 #automountServiceAccountToken: false
 
 
#kubectl create serviceaccount dashboard-sa
#kubectl create token dashboard-sa


---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: dashboard-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io


---
  
  
  
  
  
  
  









  
  
  
  
  